<?php$year=date('Y');$path=(strpos($_SERVER["HTTP_HOST"],'jamserver')!==false)?'MNKR/Member.me/':'';$protocol=(empty($_SERVER['HTTPS']))?'http':'https';$base_ref=$protocol.'://'.$_SERVER["HTTP_HOST"].'/'.$path;$token=base64_encode('mrl_'.time());$site_name='AKR Members';$logo='gfx/akr/akr_logo_badge.png';$color_bg='#222';$color_fg='#814793';$H1='Sorry, our site is currently offline.';?><!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Site Offline">
  <meta name="author" content="American Kyudo Renmei">  <base href="<?php echo $base_ref;?>"/>
  <title><?php echo $site_name;?></title>  <link rel="shortcut icon" href="<?php echo $logo;?>" type="image/x-icon">
  <!-- Bootstrap core CSS -->
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">  <!-- Custom styles for this template -->   <style>	.bd-placeholder-img {		font-size: 1.125rem;		text-anchor: middle;		-webkit-user-select: none;		-moz-user-select: none;		-ms-user-select: none;		user-select: none;	}	@media (min-width: 768px) {		.bd-placeholder-img-lg {			font-size: 3.5rem;		}	}	/* Links */	a,a:focus,a:hover {		color: #fff;	}
	/* Custom default button */	.btn-secondary,.btn-secondary:hover,.btn-secondary:focus {		color: #333;		text-shadow: none; /* Prevent inheritance from `body` */		background-color: #fff;		border: .05rem solid #fff;	}
	/* Base structure */	html,body {		height: 100%;		background-color: <?php echo $color_bg; ?>;	}	.site_logo{		padding:0.5rem;		background-color:#fff;	}	body {		display: -ms-flexbox;		display: flex;		color: <?php echo $color_fg; ?>;		text-shadow: 0 .05rem .1rem rgba(0, 0, 0, .5);		box-shadow: inset 0 0 5rem rgba(0, 0, 0, .5);	}	#myModal{		color: #A52A2A;	}	.cover-container {		max-width: 42em;	}	/* Header */	.masthead {		margin-bottom: 2rem;	}	.masthead-brand {		margin-bottom: 0;	}	.nav-masthead .nav-link {		padding: .25rem 0;		font-weight: 700;		color: rgba(199, 0, 37, .5);		background-color: transparent;		border-bottom: .25rem solid transparent;	}	.nav-masthead .nav-link:hover,.nav-masthead .nav-link:focus {		border-bottom-color: rgba(255, 255, 255, .25);	}	.nav-masthead .nav-link + .nav-link {		margin-left: 1rem;	}	.nav-masthead .active {		color: <?php echo $color_fg; ?>;		border-bottom-color: <?php echo $color_fg; ?>;	}	.logo{height:auto; max-height:12rem; margin-bottom:1.5rem;}	@media (min-width: 48em) {		.masthead-brand {float: left;}		.nav-masthead {float: right;}	}	/* Cover */	.cover {		padding: 0 1.5rem;  	}	.cover .btn-lg {		padding: .75rem 1.25rem;		font-weight: 700;	}	.scroller{		max-height:45vh;		overflow-y:auto;	}	/* Footer */	.mastfoot {		color: <?php echo $color_fg; ?>;	}	.card {		background-color:transparent!important;		border:0;		text-shadow:none;		padding-bottom:0.5rem;	}  </style>
</head><body class="text-center">	<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">		<!-- Navigation -->		<header class="masthead mb-auto">			<div class="inner">				<h3 class="masthead-brand"><?php echo $site_name; ?></h3>				<nav class="nav nav-masthead justify-content-center">					<a class="nav-link active" href="#nogo">offline</a>				</nav>			</div>		</header>		<main role="main" class="inner cover">			<img class="logo" src="<?php echo $logo; ?>">
			<h1 class="cover-heading"><?php echo $H1; ?></h1>			<p class="lead">Please try again a bit later...</p>		</main>		<footer class="mastfoot mt-auto">			<div class="inner">				<p data-toggle="modal" data-target="#myModal"><?php echo $site_name; ?> &copy; <?php echo $year; ?></p>			</div>		</footer>
	</div>		<!-- Modal -->	<div id="myModal" class="modal fade" role="dialog">	  <div class="modal-dialog">		<!-- Modal content-->		<div class="modal-content">		  <div class="modal-header">			<h4 class="modal-title">Login</h4>			<button type="button" class="close" data-dismiss="modal">&times;</button>		  </div>		  <form method="POST" action="<?php echo $base_ref; ?>">			  <input type="hidden" name="token_ol" value="<?php echo $token; ?>"/>			  <input type="hidden" name="action" value="login"/>			  <div class="modal-body">				  <label>Username:	<input type="text" name="uname_ol"/></label>				  <label>Password:	<input type="password" name="pass_ol"/></label>			  </div>			  <div class="modal-footer">				<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>				<button type="submit" class="btn btn-success">Login</button>			  </div> 		  </form>		</div>	  </div>	</div>	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>	</body>
</html>